import { useEffect, useState } from 'react';
export function AchievementNotificationSettings({locale}:{locale:'fr'|'en'}) {
  const desktop=window.nexusDesktop,fr=locale==='fr';const [enabled,setEnabled]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{let alive=true;void desktop?.getAchievementNotificationSettings?.().then(value=>{if(alive)setEnabled(value.enabled);}).catch(()=>{if(alive)setMessage(fr?'Réglages indisponibles.':'Settings unavailable.');});return()=>{alive=false;};},[desktop,fr]);
  const change=async(value:boolean)=>{if(!desktop)return;setBusy(true);try{const prefs=await desktop.setAchievementNotificationSettings({enabled:value,locale});setEnabled(prefs.enabled);setMessage('');}catch{setMessage(fr?'Impossible d’enregistrer.':'Could not save settings.');}finally{setBusy(false);}};
  const preview=async()=>{if(!desktop)return;setBusy(true);try{await desktop.testAchievementNotification(locale);setMessage(fr?'Aperçu de test affiché ; aucun succès n’est enregistré.':'Test preview shown; no achievement was recorded.');}catch{setMessage(fr?'Aperçu indisponible.':'Preview unavailable.');}finally{setBusy(false);}};
  if(!desktop?.getAchievementNotificationSettings)return null;
  return <section className="achievement-notification-settings"><h3>{fr?'Notifications pendant le jeu':'In-game notifications'}</h3><label><input type="checkbox" checked={enabled} disabled={busy} onChange={event=>void change(event.target.checked)}/>{fr?'Afficher les nouveaux succès Steam':'Show new Steam achievements'}</label><p>{fr?'Pour les jeux lancés depuis Nexus, après activation de la synchronisation Steam. Le délai dépend de Steam. Affichage prévu en mode fenêtré ou sans bordures ; le plein écran exclusif peut masquer la notification.':'For games launched through Nexus, after enabling Steam synchronization. Timing depends on Steam. Intended for windowed or borderless games; exclusive fullscreen may hide the notification.'}</p><button className="settings-inline-action" disabled={busy} type="button" onClick={()=>void preview()}>{fr?'Tester la notification':'Test notification'}</button><p role="status">{message}</p></section>;
}
