import {readFile,writeFile,mkdir,rename,rm,realpath,stat} from 'node:fs/promises';
import {join,dirname,relative,isAbsolute} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {unpackVerifiedZip} from './zipPackage.mjs';
const repository='zamakz641-byte/Nexus-Launcher',id='nexus-replay';
const indexUrl=`https://raw.githubusercontent.com/${repository}/main/plugins/catalog.json`;
const inside=(file,root)=>{const path=relative(root,file);return !!path&&!isAbsolute(path)&&path!=='..'&&!path.startsWith('..\\')&&!path.startsWith('../');};
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
export class PluginManager{
 constructor(dir,{fetch=globalThis.fetch,platform=process.platform}={}){this.root=join(dir,'plugins');this.file=join(this.root,'registry.json');this.fetch=fetch;this.platform=platform;this.state='idle';this.progress=0;this.writes=Promise.resolve();}
 async preferences(){try{return JSON.parse(await readFile(this.file,'utf8'));}catch{return {enabled:false};}}
 save(prefs){const task=this.writes.then(async()=>{await mkdir(this.root,{recursive:true});await writeFile(this.file+'.tmp',JSON.stringify(prefs),'utf8');await rename(this.file+'.tmp',this.file);});this.writes=task.catch(()=>{});return task;}
 async bytes(url,limit,signal){const response=await this.fetch(url,{signal});if(!response.ok||!response.body)throw Error('download-unavailable');const reader=response.body.getReader(),chunks=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>limit)throw Error('package-too-large');chunks.push(Buffer.from(value));if(this.state==='downloading'&&this.release?.manifest?.downloadBytes)this.progress=Math.min(99,Math.floor(total/this.release.manifest.downloadBytes*100));}}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}return Buffer.concat(chunks,total);}
 async resolveRelease(signal){
  if(this.release&&Date.now()<this.releaseExpires)return this.release;
  const catalog=JSON.parse((await this.bytes(indexUrl,65536,signal)).toString('utf8'));
  const item=catalog?.schema===1&&catalog.plugins?.find(plugin=>plugin.id===id);
  if(!item||!/^\d+\.\d+\.\d+$/.test(item.version)||item.tag!==`plugin-${id}-v${item.version}`||item.manifest!==`${id}.json`)throw Error('invalid-catalog');
  const api=`https://api.github.com/repos/${repository}/releases/tags/${item.tag}`,data=JSON.parse((await this.bytes(api,1024**2,signal)).toString('utf8'));
  const assetFor=name=>{const asset=data.assets?.find(asset=>asset.name===name);const prefix=`https://github.com/${repository}/releases/download/${item.tag}/`;if(!asset||asset.browser_download_url!==prefix+name||!/^sha256:[a-f0-9]{64}$/.test(asset.digest)||!Number.isSafeInteger(asset.size))throw Error('invalid-release');return asset;};
  const manifestAsset=assetFor(item.manifest),raw=await this.bytes(manifestAsset.browser_download_url,65536,signal);if(raw.length!==manifestAsset.size||sha(raw)!==manifestAsset.digest.slice(7))throw Error('checksum-mismatch');
  const manifest=JSON.parse(raw.toString('utf8')),asset=assetFor(`nexus-replay-${item.version}-win-x64.zip`);
  if(manifest.schema!==1||manifest.id!==id||manifest.version!==item.version||manifest.protocol!==1||manifest.entry!=='NexusReplay.exe'||manifest.license!=='GPL-3.0-only'||manifest.asset!==asset.name||manifest.downloadBytes!==asset.size||asset.size>100*1024**2||manifest.sha256!==asset.digest.slice(7)||!Number.isSafeInteger(manifest.installedBytes)||manifest.installedBytes>150*1024**2||!Array.isArray(manifest.files)||!manifest.files.some(file=>file.path===manifest.entry)||manifest.files.some(file=>file.path==='plugin.json'))throw Error('invalid-manifest');
  this.release={manifest,asset,tag:item.tag};this.releaseExpires=Date.now()+300000;return this.release;
 }
 async installation(){const prefs=await this.preferences();if(!prefs.installation||!/^nexus-replay-[a-f0-9-]{36}$/.test(prefs.installation))return null;const folder=join(this.root,prefs.installation);try{const canonical=await realpath(folder);if(!inside(canonical,await realpath(this.root)))return null;const manifest=JSON.parse(await readFile(join(folder,'plugin.json'),'utf8'));if(manifest.id!==id||manifest.entry!=='NexusReplay.exe')return null;const exe=join(folder,manifest.entry);if(!(await stat(exe)).isFile())return null;return {folder,manifest,exe};}catch{return null;}}
 async status({refresh=false}={}){const installed=await this.installation(),prefs=await this.preferences();if(refresh&&Date.now()>(this.nextRefresh||0)){this.nextRefresh=Date.now()+300000;try{await this.resolveRelease();}catch{/* Offline plugins remain usable. */}}return {id,installed:!!installed,enabled:!!installed&&prefs.enabled===true,supported:this.platform==='win32',state:this.state,progress:this.progress,error:this.error,version:installed?.manifest.version,availableVersion:this.release?.manifest.version,available:!!this.release,downloadBytes:this.release?.manifest.downloadBytes,installedBytes:installed?.manifest.installedBytes||this.release?.manifest.installedBytes,license:'GPL-3.0-only'};}
 async executable(){const installed=await this.installation();if(!installed)throw Error('plugin-missing');for(const file of installed.manifest.files){const path=join(installed.folder,file.path);if(!inside(await realpath(path),await realpath(installed.folder))||sha(await readFile(path))!==file.sha256)throw Error('plugin-modified');}return installed.exe;}
 activate(){if(this.pending)return this.pending;this.pending=this.install().finally(()=>{this.pending=null;});return this.pending;}
 async install(){const previous=await this.installation();let staging;this.error=undefined;this.controller=new AbortController();try{if(this.platform!=='win32')throw Error('unsupported');this.state='downloading';this.progress=0;const {manifest,asset}=await this.resolveRelease(this.controller.signal);const zip=await this.bytes(asset.browser_download_url,manifest.downloadBytes,this.controller.signal);if(zip.length!==manifest.downloadBytes||sha(zip)!==manifest.sha256)throw Error('checksum-mismatch');this.state='installing';const entries=unpackVerifiedZip(zip,manifest.files);if(entries.reduce((total,file)=>total+file.bytes.length,0)!==manifest.installedBytes)throw Error('invalid-manifest');await mkdir(this.root,{recursive:true});const key=`nexus-replay-${randomUUID()}`;staging=join(this.root,key);await mkdir(staging);for(const entry of entries){const target=join(staging,entry.path);await mkdir(dirname(target),{recursive:true});await writeFile(target,entry.bytes,{flag:'wx'});}await writeFile(join(staging,'plugin.json'),JSON.stringify(manifest),{flag:'wx'});if(this.controller.signal.aborted)throw Error('cancelled');await this.save({enabled:true,installation:key});staging=null;if(previous)await this.removeOwned(previous.folder).catch(()=>{});this.state='ready';this.progress=100;}catch(error){this.state=this.controller.signal.aborted?'cancelled':'error';this.error=['unsupported','checksum-mismatch','invalid-package','invalid-manifest','plugin-modified'].includes(error.message)?error.message:'download-unavailable';}finally{if(staging)await this.removeOwned(staging);this.controller=null;}return this.status();}
 cancel(){this.controller?.abort();}
 async enable(value){if(typeof value!=='boolean')throw Error('invalid-preference');if(value)await this.executable();await this.save({...await this.preferences(),enabled:value});return this.status();}
 async removeOwned(path){const root=await realpath(this.root),target=await realpath(path).catch(()=>null);if(target&&inside(target,root)&&/^nexus-replay-[a-f0-9-]{36}$/.test(relative(root,target)))await rm(target,{recursive:true,force:true});}
 async remove(){const installed=await this.installation();await this.save({enabled:false});if(installed)await this.removeOwned(installed.folder);this.state='idle';return this.status();}
}
