const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("nexusDesktop", Object.freeze({
  chooseLibraryFolder: () => ipcRenderer.invoke("nexus:choose-library"),
  addGameFolder: () => ipcRenderer.invoke("nexus:add-game-folder"),
  scanLibrary: (sourceId, force = false) => ipcRenderer.invoke("nexus:library-scan", sourceId, force),
  listLibrary: () => ipcRenderer.invoke("nexus:library-list"),
  onLibraryChanged: (callback) => { const listener = (_event, payload) => callback(payload); ipcRenderer.on("nexus:library-changed", listener); return () => ipcRenderer.removeListener("nexus:library-changed", listener); },
  addGameExecutable: () => ipcRenderer.invoke("nexus:add-executable"),
  removeLibraryEntry: (id) => ipcRenderer.invoke("nexus:library-remove", id),
  setGameTitle: (id, title) => ipcRenderer.invoke("nexus:game-title", id, title),
  chooseGameExecutable: (id) => ipcRenderer.invoke("nexus:game-executable", id),
  chooseGameArtwork: (id, role) => ipcRenderer.invoke("nexus:game-artwork", id, role),
  getSteamGridStatus: () => ipcRenderer.invoke("nexus:steamgrid-status"),
  getSteamAccountStatus: () => ipcRenderer.invoke("nexus:steam-account-status"),
  connectSteamAccount: () => ipcRenderer.invoke('nexus:steam-account-connect'),
  cancelSteamConnection: () => ipcRenderer.invoke('nexus:steam-account-cancel'),
  onSteamDataChanged: (callback) => { const listener = () => callback(); ipcRenderer.on('nexus:steam-data-changed',listener);return () => ipcRenderer.removeListener('nexus:steam-data-changed',listener); },
  getAchievementNotificationSettings: () => ipcRenderer.invoke('nexus:achievement-notification-settings'),
  setAchievementNotificationSettings: (value) => ipcRenderer.invoke('nexus:achievement-notification-save',value),
  testAchievementNotification: (locale) => ipcRenderer.invoke('nexus:achievement-notification-test',locale),
  getSteamNotificationStatus: () => ipcRenderer.invoke('nexus:steam-notification-status'),
  activateSteamNotifications: () => ipcRenderer.invoke('nexus:steam-notification-activate'),
  cancelSteamNotificationSetup: () => ipcRenderer.invoke('nexus:steam-notification-cancel'),
  openSteam: () => ipcRenderer.invoke('nexus:steam-open'),
  getSanCompanionStatus: () => ipcRenderer.invoke('nexus:san-status'),
  chooseSanExecutable: () => ipcRenderer.invoke('nexus:san-choose'),
  setSanCompanionEnabled: (enabled) => ipcRenderer.invoke('nexus:san-enable',enabled),
  launchSanCompanion: () => ipcRenderer.invoke('nexus:san-launch'),
  openSanDownload: () => ipcRenderer.invoke('nexus:san-download'),
  getSteamLibrary: (force = false) => ipcRenderer.invoke('nexus:steam-library', force),
  getGameActivity: (gameId) => ipcRenderer.invoke('nexus:game-activity', gameId),
  getModuleStatus: () => ipcRenderer.invoke('nexus:module-status'),
  listCaptures: () => ipcRenderer.invoke('nexus:capture-list'),
  captureScreenshot: (locale) => ipcRenderer.invoke('nexus:capture-screenshot',locale),
  addCaptureFolder: () => ipcRenderer.invoke('nexus:capture-folder'),
  favoriteCapture: (id,value) => ipcRenderer.invoke('nexus:capture-favorite',id,value),
  revealCapture: (id) => ipcRenderer.invoke('nexus:capture-reveal',id),
  getCaptureEngineStatus: () => ipcRenderer.invoke('nexus:capture-engine-status'),
  activateCaptureEngine: () => ipcRenderer.invoke('nexus:capture-engine-activate'),
  cancelCaptureEngineSetup: () => ipcRenderer.invoke('nexus:capture-engine-cancel'),
  disableCaptureEngine: () => ipcRenderer.invoke('nexus:capture-engine-disable'),
  removeCaptureEngine: () => ipcRenderer.invoke('nexus:capture-engine-remove'),
  saveReplay: (locale) => ipcRenderer.invoke('nexus:capture-replay',locale),
  onCaptureChanged: (callback) => { const listener=()=>callback();ipcRenderer.on('nexus:capture-changed',listener);return()=>ipcRenderer.removeListener('nexus:capture-changed',listener); },
  onActivityChanged: (callback) => { const listener = (_event,gameId) => callback(gameId); ipcRenderer.on('nexus:activity-changed',listener);return () => ipcRenderer.removeListener('nexus:activity-changed',listener); },
  getStoreAccountStatus: (provider) => ipcRenderer.invoke('nexus:store-account-status', provider),
  connectStoreAccount: (provider) => ipcRenderer.invoke('nexus:store-account-connect', provider),
  clearStoreAccount: (provider) => ipcRenderer.invoke('nexus:store-account-clear', provider),
  getStoreLibrary: (provider, force = false) => ipcRenderer.invoke('nexus:store-library', provider, force),
  clearSteamAccount: () => ipcRenderer.invoke("nexus:steam-account-clear"),
  getSteamAchievements: (appId, locale, force = false) => ipcRenderer.invoke("nexus:steam-achievements", appId, locale, force),
  saveSteamGridKey: (value) => ipcRenderer.invoke("nexus:steamgrid-save", value),
  clearSteamGridKey: () => ipcRenderer.invoke("nexus:steamgrid-clear"),
  searchCatalog: (query) => ipcRenderer.invoke("nexus:catalog-search", query),
  system: () => ipcRenderer.invoke("nexus:system-info"),
  launchGame: (gameId, locale) => ipcRenderer.invoke("nexus:launch-game", gameId, locale),
  platform: process.platform,
}));
