// @vitest-environment jsdom
import React from 'react';
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import {afterEach,expect,test,vi} from 'vitest';
import {CapturesScreen} from './CapturesScreen';
import {useNexusStore} from '../state/useNexusStore';
import type {CaptureItem} from '../captureTypes';
const media: CaptureItem[]=[{id:'image',kind:'image',name:'screen.png',game:'My Game',source:'Nexus',createdAt:'2026-10-06T12:00:00Z',bytes:200,favorite:false,url:'nexus://media/capture?id=image'},{id:'clip',kind:'clip',name:'replay.mp4',game:'Other Game',source:'GameHQ',createdAt:'2026-10-06T11:00:00Z',bytes:1000,favorite:true,url:'nexus://media/capture?id=clip'}];
function fixture(){let items=media.map(x=>({...x}));const api={listCaptures:vi.fn().mockImplementation(async()=>({items,roots:[],errors:[],truncated:false})),getCaptureEngineStatus:vi.fn().mockResolvedValue({installed:false,enabled:false,supported:true,state:'idle'}),onCaptureChanged:vi.fn(()=>()=>{}),captureScreenshot:vi.fn().mockRejectedValue(Error('failed')),favoriteCapture:vi.fn(async(id,value)=>{items=items.map(item=>item.id===id?{...item,favorite:value}:item);}),revealCapture:vi.fn(),activateCaptureEngine:vi.fn()};window.nexusDesktop=api as unknown as NonNullable<Window['nexusDesktop']>;useNexusStore.setState({locale:'en'});return api;}
afterEach(()=>{cleanup();delete window.nexusDesktop;});
test('filters actual media, plays the chosen video and changes locale live',async()=>{fixture();render(<CapturesScreen/>);await screen.findByRole('button',{name:'My Game · screen.png'});fireEvent.click(screen.getByRole('button',{name:/^Clips$/}));expect(screen.queryByRole('button',{name:'My Game · screen.png'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Other Game · replay.mp4'}));const video=document.querySelector('video')!;expect(video.getAttribute('src')).toContain('id=clip');expect(video.controls).toBe(true);useNexusStore.setState({locale:'fr'});await screen.findByRole('button',{name:'Fermer'});fireEvent.click(screen.getByRole('button',{name:'Fermer'}));await waitFor(()=>expect(document.querySelector('video')).toBeNull());});
test('favorite changes persist and an empty favorite filter closes its viewer',async()=>{const api=fixture();render(<CapturesScreen/>);await screen.findByRole('button',{name:'My Game · screen.png'});fireEvent.click(screen.getByRole('button',{name:/^Favorites$/}));fireEvent.click(screen.getByRole('button',{name:'Other Game · replay.mp4'}));fireEvent.click(screen.getByRole('button',{name:'Remove from favorites'}));await screen.findByText('No moments found');expect(api.favoriteCapture).toHaveBeenCalledWith('clip',false);await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());});
test('failed screenshot never announces success and controls recover',async()=>{fixture();render(<CapturesScreen/>);await screen.findByRole('button',{name:'My Game · screen.png'});fireEvent.click(screen.getByRole('button',{name:'Capture screen'}));await screen.findByText('Unable to finish. Please retry.');expect(screen.queryByText('Screenshot saved')).toBeNull();await waitFor(()=>expect(screen.getByRole('button',{name:'Capture screen'}).hasAttribute('disabled')).toBe(false));});
