import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {unpackVerifiedZip} from '../backend/plugins/zipPackage.mjs';
import {PluginManager} from '../backend/plugins/pluginManager.mjs';
import {ReplayRuntime} from '../backend/plugins/replayRuntime.mjs';
const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
function archive(path,bytes){const name=Buffer.from(path),local=Buffer.alloc(30),central=Buffer.alloc(46),end=Buffer.alloc(22);local.writeUInt32LE(0x04034b50);local.writeUInt32LE(bytes.length,18);local.writeUInt32LE(bytes.length,22);local.writeUInt16LE(name.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt32LE(bytes.length,20);central.writeUInt32LE(bytes.length,24);central.writeUInt16LE(name.length,28);const offset=30+name.length+bytes.length;end.writeUInt32LE(0x06054b50);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(46+name.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([local,name,bytes,central,name,end]);}
const payload=Buffer.from('fixture exe'),files=[{path:'NexusReplay.exe',size:payload.length,sha256:digest(payload)}];
test('ZIP accepts only the exact manifest, rejects traversal, tampering and oversized output',()=>{assert.deepEqual(unpackVerifiedZip(archive('NexusReplay.exe',payload),files)[0].bytes,payload);assert.throws(()=>unpackVerifiedZip(archive('../escape.exe',payload),files));assert.throws(()=>unpackVerifiedZip(archive('NexusReplay.exe',Buffer.from('tamperedexe')),files));assert.throws(()=>unpackVerifiedZip(archive('NexusReplay.exe',payload),[{...files[0],size:151*1024**2}]));assert.throws(()=>unpackVerifiedZip(archive('NexusReplay.exe',payload),[{...files[0],path:'C:/evil.exe'}]));});
test('install replaces its owned package; uninstall keeps captures; modified binary is rejected',async()=>{const dir=await mkdtemp(join(tmpdir(),'nexus-plugin-'));try{const manager=new PluginManager(dir,{platform:'win32'}),zip=archive('NexusReplay.exe',payload);manager.resolveRelease=async()=>({manifest:{id:'nexus-replay',version:'0.1.0',entry:'NexusReplay.exe',files,downloadBytes:zip.length,installedBytes:payload.length,sha256:digest(zip)},asset:{browser_download_url:'fixture'}});manager.bytes=async()=>zip;await manager.activate();const first=await manager.installation();assert.ok(first);await manager.activate();const second=await manager.installation();assert.notEqual(first.folder,second.folder);assert.equal(await import('node:fs/promises').then(fs=>fs.stat(first.folder).catch(()=>null)),null);await writeFile(second.exe,'changed');await assert.rejects(manager.executable(),/modified/);await manager.remove();assert.equal((await manager.status()).installed,false);}finally{await rm(dir,{recursive:true,force:true});}});
test('shutdown drains an explicit export including media adoption before stopping its owned child',async()=>{const runtime=new ReplayRuntime({root:'unused'},{capturesRoot:'unused',onSaved:async()=>{}}),child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{child.killed=true;child.emit('exit');};child.exitCode=null;runtime.child=child;runtime.ready=true;runtime.stopping=false;let command;child.stdin.on('data',line=>{command=JSON.parse(line.toString());if(command.type==='shutdown')child.emit('exit');});const save=runtime.send('save-replay');const saveCommand=command;let closed=false;const shutdown=runtime.disconnect().then(()=>closed=true);await new Promise(resolve=>setImmediate(resolve));assert.equal(closed,false);assert.equal(command.type,'save-replay');const pending=runtime.requests.get(saveCommand.requestId);clearTimeout(pending.timer);runtime.requests.delete(saveCommand.requestId);pending.resolve({ok:true});await save;await shutdown;assert.equal(command.type,'shutdown');assert.equal(child.killed,undefined);});
test('disabling during executable verification prevents a late process spawn',async()=>{const dir=await mkdtemp(join(tmpdir(),'nexus-replay-'));let resolveExe,enabled=true,launches=0;const manager={root:dir,status:async()=>({enabled}),executable:()=>new Promise(resolve=>resolveExe=resolve),enable:async value=>enabled=value,cancel(){}};const runtime=new ReplayRuntime(manager,{capturesRoot:dir,spawn:()=>{launches++;}});try{const starting=runtime.ensureStarted();while(!resolveExe)await new Promise(resolve=>setImmediate(resolve));await runtime.enable(false);resolveExe(join(dir,'engine.exe'));await starting;assert.equal(launches,0);}finally{await rm(dir,{recursive:true,force:true});}});
