import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {EventEmitter} from 'node:events';
import {SanCompanion} from '../backend/sanCompanion.mjs';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'nexus-san-'));const programs=join(root,'Programs'),dir=join(programs,'Steam Achievement Notifier (V1.9)');await mkdir(dir,{recursive:true});const exe=join(dir,'Steam Achievement Notifier (V1.9).exe');await writeFile(exe,'fixture');let launches=0;const spawn=()=>{launches++;const child=new EventEmitter();child.unref=()=>{};queueMicrotask(()=>child.emit('spawn'));return child;};return {root,exe,service:new SanCompanion(root,{platform:'win32',programRoots:[programs],spawn,isRunning:async()=>false}),launches:()=>launches};}
test('detects installed SAN, persists opt-in and launches once for concurrent Steam launches',async()=>{const f=await fixture();try{assert.equal((await f.service.status()).enabled,false);assert.equal((await f.service.status()).installed,true);assert.equal((await f.service.ensureStarted()).state,'disabled');await f.service.enable(true);const values=await Promise.all([f.service.ensureStarted(),f.service.ensureStarted()]);assert.ok(values.every(x=>x.state==='running'));assert.equal(f.launches(),1);const reopened=new SanCompanion(f.root,{platform:'win32',programRoots:[]});assert.equal((await reopened.status()).enabled,true);}finally{await rm(f.root,{recursive:true,force:true});}});
test('rejects installers and missing executables, disabling never deletes SAN',async()=>{const f=await fixture();try{await assert.rejects(f.service.choose(join(f.root,'SteamAchievementNotifier_V1.9.46.exe')));await assert.rejects(f.service.choose(join(f.root,'Steam Achievement Notifier.exe')));await f.service.choose(f.exe);await f.service.enable(true);await f.service.enable(false);assert.equal((await f.service.status()).installed,true);assert.equal((await f.service.ensureStarted()).state,'disabled');assert.equal(f.launches(),0);}finally{await rm(f.root,{recursive:true,force:true});}});
test('missing SAN cannot enable and a failed spawn is reported honestly',async()=>{const f=await fixture();try{const missing=new SanCompanion(join(f.root,'empty'),{platform:'win32',programRoots:[]});await assert.rejects(missing.enable(true));await f.service.enable(true);f.service.spawn=()=>{const child=new EventEmitter();queueMicrotask(()=>child.emit('error',new Error('blocked')));return child;};assert.equal((await f.service.ensureStarted()).state,'error');}finally{await rm(f.root,{recursive:true,force:true});}});
