import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {LocalSteamProgress} from '../backend/steamLocal.mjs';
const id='76561198000000000',user=String(BigInt(id)-76561197960265728n);
async function fixture(){const root=await mkdtemp(join(tmpdir(),'nexus-steam-local-')),steam=join(root,'Steam');await mkdir(join(steam,'config'),{recursive:true});await mkdir(join(steam,'userdata',user,'config','librarycache'),{recursive:true});await mkdir(join(steam,'steamapps'),{recursive:true});await writeFile(join(steam,'config','loginusers.vdf'),`"users" {"${id}" {"MostRecent" "1"}}`);await writeFile(join(steam,'userdata',user,'config','localconfig.vdf'),'"UserLocalConfigStore" {"Software" {"Valve" {"Steam" {"apps" {"10" {"Playtime" "125"} "20" {"Playtime" "0"}}}}}}');await writeFile(join(steam,'steamapps','appmanifest_10.acf'),'"AppState" {"appid" "10" "name" "Real Game"}');return {root,steam,service:new LocalSteamProgress(root,{roots:async()=>[steam]})};}
test('reads historical local Steam minutes including zero with no key or network request',async()=>{const f=await fixture();try{assert.equal((await f.service.status()).configured,true);const value=await f.service.getLibrary(true);assert.equal(value.state,'ready');assert.equal(value.games.find(x=>x.id==='10').playtimeMinutes,125);assert.equal(value.games.find(x=>x.id==='20').playtimeMinutes,0);await f.service.clearAccount();assert.equal((await f.service.getLibrary()).state,'unconfigured');await f.service.connect();assert.equal((await f.service.status()).linked,true);}finally{await rm(f.root,{recursive:true,force:true});}});
test('reports partial cached achievement lists honestly and does not reveal hidden locked descriptions',async()=>{const f=await fixture();try{await writeFile(join(f.steam,'userdata',user,'config','librarycache','10.json'),JSON.stringify([['achievements',{version:1,data:{nTotal:15,nAchieved:4,vecHighlight:[{strID:'A',strName:'Win',strDescription:'Done',bAchieved:true,rtUnlocked:123}],vecUnachieved:[{strID:'B',strName:'Secret',strDescription:'Spoiler',bAchieved:false,bHidden:true}],vecAchievedHidden:[]}}]]));const value=await f.service.getAchievements(10,'en');assert.equal(value.total,15);assert.equal(value.unlockedCount,4);assert.equal(value.cached,true);assert.equal(value.achievements.find(x=>x.id==='A').unlocked,true);assert.equal(value.achievements.find(x=>x.id==='B').description,'');assert.equal((await f.service.getAchievements(20)).state,'unavailable');}finally{await rm(f.root,{recursive:true,force:true});}});
test('absent Steam cache is unavailable, never invented as zero playtime or zero achievements',async()=>{const f=await fixture();try{await rm(join(f.steam,'userdata',user,'config','localconfig.vdf'));assert.equal((await f.service.getLibrary()).games.find(x=>x.id==='10').playtimeMinutes,undefined);assert.equal((await f.service.getAchievements(10)).state,'unavailable');}finally{await rm(f.root,{recursive:true,force:true});}});

test('new Steam login cache without MostRecent uses the saved current account',async()=>{const f=await fixture();try{await writeFile(join(f.steam,'config','loginusers.vdf'),`"users" {"${id}" {"AutoLogin" "1" "Timestamp" "1234"}}`);assert.equal((await f.service.getLibrary()).games.find(x=>x.id==='10').playtimeMinutes,125);}finally{await rm(f.root,{recursive:true,force:true});}});
