export const captureCopy = {
 fr: {
 title:'Captures',subtitle:'Vos meilleurs moments.',all:'Tout',images:'Captures',clips:'Clips',favorites:'Favoris',allGames:'Tous les jeux',search:'Rechercher',refresh:'Actualiser',screenshot:'Capturer l’écran',addFolder:'Ajouter un dossier',
 engine:'Nexus Replay',engineHint:'Enregistrez les 30 dernières secondes de votre jeu.',enable:'Activer',install:'Télécharger',disable:'Désactiver',ready:'Prêt · Lancez un jeu depuis Nexus',recording:'Enregistrement en cours · 720p / 30 fps',waiting:'Recherche de la fenêtre du jeu…',remove:'Désinstaller',help:'Détails du plugin',helpText:'Moteur dérivé de GameHQ · GPL-3.0. Téléchargement depuis notre GitHub. Buffer de 30 s, sans audio dans cette première version. Le raccourci F9 sauvegarde un clip ; F8 prend une capture. Le jeu doit être lancé depuis Nexus. Les notifications fonctionnent en mode fenêtré ou sans bordure.',pending:'Bientôt disponible',sizePending:'Poids affiché à la publication du plugin',disk:'sur disque',saveReplay:'Sauvegarder le replay',replayShortcut:'Ctrl + Maj + F9 · 30 dernières secondes',
 empty:'Le prochain moment est à vous.',emptyHint:'Prenez une capture ou ajoutez votre dossier de clips.',desktop:'Bureau',loading:'Chargement…',busy:'Un instant…',installing:'Installation…',downloading:'Téléchargement…',cancel:'Annuler',error:'Impossible de terminer. Réessayez.',saved:'Média enregistré',reveal:'Voir dans l’explorateur',favorite:'Ajouter aux favoris',unfavorite:'Retirer des favoris',close:'Fermer',previous:'Précédent',next:'Suivant',shortcut:'Ctrl + Maj + F8',limit:'Les 500 médias les plus récents sont affichés.',sourceError:'Un dossier est indisponible.',noResults:'Aucun moment trouvé',viewer:'Aperçu du média',readError:'Ce média ne peut pas être lu.',browser:'Disponible dans l’application Windows',unsupported:'Nexus Replay nécessite Windows.',plugins:'Plugins',pluginSubtitle:'Ajoutez seulement ce dont vous avez besoin.',source:'Code source',
 },
 en: {
 title:'Captures',subtitle:'Your best moments.',all:'All',images:'Screenshots',clips:'Clips',favorites:'Favorites',allGames:'All games',search:'Search',refresh:'Refresh',screenshot:'Capture screen',addFolder:'Add folder',
 engine:'Nexus Replay',engineHint:'Keep the last 30 seconds of your game.',enable:'Enable',install:'Download',disable:'Disable',ready:'Ready · Launch a game from Nexus',recording:'Recording · 720p / 30 fps',waiting:'Waiting for the game window…',remove:'Uninstall',help:'Plugin details',helpText:'Based on GameHQ · GPL-3.0. Downloaded from our GitHub. 30-second buffer, without audio in this first version. F9 saves a replay; F8 takes a screenshot. Launch the game from Nexus. Notifications work in windowed or borderless mode.',pending:'Coming soon',sizePending:'Package size appears when the plugin is published',disk:'on disk',saveReplay:'Save replay',replayShortcut:'Ctrl + Shift + F9 · Last 30 seconds',
 empty:'Your next moment awaits.',emptyHint:'Take a screenshot or add your clips folder.',desktop:'Desktop',loading:'Loading…',busy:'One moment…',installing:'Installing…',downloading:'Downloading…',cancel:'Cancel',error:'Unable to finish. Please retry.',saved:'Media saved',reveal:'Show in Explorer',favorite:'Add to favorites',unfavorite:'Remove from favorites',close:'Close',previous:'Previous',next:'Next',shortcut:'Ctrl + Shift + F8',limit:'Showing the 500 most recent media files.',sourceError:'A folder is unavailable.',noResults:'No moments found',viewer:'Media preview',readError:'This media cannot be played.',browser:'Available in the Windows app',unsupported:'Nexus Replay requires Windows.',plugins:'Plugins',pluginSubtitle:'Add only what you need.',source:'Source code',
 }
} as const;
