from pathlib import Path
p=Path(r"C:\Users\USER\Downloads\Compressed\NexusLauncher_v1.6.7_STARTUP_SFX_SYNC\index.html")
s=p.read_text(encoding='utf-8')
s=s.replace('width: 78px;\n        height: 78px;', 'width: 96px;\n        height: 96px;', 1)
s=s.replace('width: 80px;\n        height: 80px;', 'width: 94px;\n        height: 94px;', 1)
s=s.replace('.nexus-boot-n { stroke: #58cafa; stroke-width: 17;', '.nexus-boot-n { stroke: #7cddff; stroke-width: 19;')
s=s.replace('html.nexus-boot-live .nexus-boot-hex { animation: nexusBootDraw .82s .12s cubic-bezier(.16,1,.3,1) forwards; }', 'html.nexus-boot-live .nexus-boot-hex { animation: nexusBootDraw .66s .30s cubic-bezier(.16,1,.3,1) forwards; }')
s=s.replace('html.nexus-boot-live .nexus-boot-orbit { animation: nexusBootDraw .72s .30s cubic-bezier(.16,1,.3,1) forwards; }', 'html.nexus-boot-live .nexus-boot-orbit { animation: nexusBootDraw .58s .48s cubic-bezier(.16,1,.3,1) forwards; }')
s=s.replace('html.nexus-boot-live .nexus-boot-n { animation: nexusBootDraw .62s .54s cubic-bezier(.16,1,.3,1) forwards; }', 'html.nexus-boot-live .nexus-boot-n { animation: nexusBootDraw .54s .06s cubic-bezier(.16,1,.3,1) forwards; }')
s=s.replace('html.nexus-boot-live .nexus-boot-pillars { animation: nexusBootDraw .46s .72s cubic-bezier(.16,1,.3,1) forwards; }', 'html.nexus-boot-live .nexus-boot-pillars { animation: nexusBootDraw .38s .18s cubic-bezier(.16,1,.3,1) forwards; }')
s=s.replace('html.nexus-boot-live .nexus-boot-node { animation: nexusBootNode .42s 1.04s cubic-bezier(.16,1,.3,1) forwards; }', 'html.nexus-boot-live .nexus-boot-node { animation: nexusBootNode .34s .72s cubic-bezier(.16,1,.3,1) forwards; }')
s=s.replace('html.nexus-boot-live .nexus-boot-mark-flare { animation: nexusBootFlare .56s 1.00s cubic-bezier(.16,1,.3,1) both; }', 'html.nexus-boot-live .nexus-boot-mark-flare { animation: nexusBootFlare .50s .70s cubic-bezier(.16,1,.3,1) both; }')
s=s.replace('html.nexus-boot-live .nexus-boot-wordmark { animation: nexusBootWord .52s 1.02s cubic-bezier(.16,1,.3,1) both; }', 'html.nexus-boot-live .nexus-boot-wordmark { animation: nexusBootWord .48s .82s cubic-bezier(.16,1,.3,1) both; }')
s=s.replace('html.nexus-boot-live .nexus-boot-tagline { animation: nexusBootWord .46s 1.24s cubic-bezier(.16,1,.3,1) both; }', 'html.nexus-boot-live .nexus-boot-tagline { animation: nexusBootWord .40s 1.04s cubic-bezier(.16,1,.3,1) both; }')
p.write_text(s,encoding='utf-8')
print('startup reordered: N first, frame second')
